import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  heroContent: defineTable({
    title: v.optional(v.string()),
    subtitle: v.optional(v.string()),
    description: v.optional(v.string()),
    roles: v.optional(v.array(v.string())),
    ctaText: v.optional(v.string()),
    ctaLink: v.optional(v.string()),
    secondaryCtaText: v.optional(v.string()),
    secondaryCtaLink: v.optional(v.string()),
    lastUpdated: v.optional(v.number()),
  }),
  aboutContent: defineTable({
    title: v.optional(v.string()),
    subtitle: v.optional(v.string()),
    bio: v.optional(v.any()), // string or array<string>
    paragraphs: v.optional(v.array(v.string())),
    imageUrl: v.optional(v.string()),
    highlights: v.optional(
      v.array(
        v.object({
          icon: v.optional(v.string()),
          title: v.optional(v.string()),
          value: v.optional(v.string()),
          description: v.optional(v.string()),
          color: v.optional(v.string()),
        })
      )
    ),
    stats: v.optional(v.any()), // Map<String, dynamic>
    lastUpdated: v.optional(v.number()),
  }),
  socialLinks: defineTable({
    platform: v.optional(v.string()),
    name: v.optional(v.string()),
    url: v.optional(v.string()),
    href: v.optional(v.string()),
    icon: v.optional(v.string()),
    username: v.optional(v.string()),
    label: v.optional(v.string()),
    color: v.optional(v.string()),
    isActive: v.optional(v.boolean()),
    order: v.optional(v.number()),
    lastUpdated: v.optional(v.number()),
  }),
  skills: defineTable({
    name: v.string(),
    category: v.string(),
    img: v.string(),
    lastUpdated: v.optional(v.number()),
  }),
  projects: defineTable({
    title: v.string(),
    category: v.string(),
    description: v.string(),
    thumbnail: v.string(),
    gallery: v.optional(v.array(v.string())),
    tags: v.array(v.string()),
    date: v.string(),
    links: v.object({
      github: v.optional(v.string()),
      demo: v.optional(v.string()),
      live: v.optional(v.string()),
    }),
    createdAt: v.optional(v.number()),
    isFeatured: v.optional(v.boolean()),
    lastUpdated: v.optional(v.number()),
  }),
  experiences: defineTable({
    title: v.string(),
    organization: v.string(),
    type: v.string(),
    location: v.string(),
    startDate: v.string(),
    endDate: v.optional(v.string()),
    isCurrent: v.optional(v.boolean()),
    description: v.string(),
    responsibilities: v.array(v.string()),
    achievements: v.array(v.string()),
    logo: v.optional(v.string()),
    color: v.optional(v.string()),
    technologies: v.array(v.string()),
    lastUpdated: v.optional(v.number()),
  }),
  hackathons: defineTable({
    title: v.string(),
    organizer: v.string(),
    description: v.string(),
    date: v.string(),
    thumbnail: v.string(),
    gallery: v.array(v.string()),
    tags: v.array(v.string()),
    links: v.object({
      github: v.optional(v.string()),
      demo: v.optional(v.string()),
      social: v.optional(v.string()),
    }),
    lastUpdated: v.optional(v.number()),
  }),
  certifications: defineTable({
    title: v.string(),
    issuer: v.string(),
    date: v.string(),
    credentialId: v.string(),
    url: v.optional(v.string()),
    iconType: v.string(),
    color: v.string(),
    glowColor: v.string(),
    skills: v.array(v.string()),
    lastUpdated: v.optional(v.number()),
  }),
});
